# Generated by Django 2.2.12 on 2020-09-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='present_year',
            field=models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], default='FE', max_length=30),
        ),
    ]
