# Generated by Django 2.2.12 on 2020-09-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_session_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField(default=0)),
            ],
        ),
    ]
